languge: node_jds
node_js:
  - 13
 
services:
  - docker


script:
  - docker --version
  - docker build . -t simple-node
  - docker tag simple-node 15huangtimothy/simple-node:latest
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 15huangtimothy/simple-node
